# Case Intro
Term deposits are a major source of income for a bank. A term deposit is a cash investment held at a financial institution. Your money is invested for an agreed rate of interest over a fixed amount of time, or term. The bank has various outreach plans to sell term deposits to their customers such as email marketing, advertisements, telephonic marketing, and digital marketing.

Telephonic marketing campaigns still remain one of the most effective way to reach out to people. However, they require huge investment as large call centers are hired to actually execute these campaigns. Hence, it is crucial to identify the customers most likely to convert beforehand so that they can be specifically targeted via call.

The data is related to direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe to a term deposit (variable y).

Content
The data is related to the direct marketing campaigns of a Portuguese banking institution. The marketing campaigns were based on phone calls. Often, more than one contact to the same client was required, in order to access if the product (bank term deposit) would be ('yes') or not ('no') subscribed by the customer or not. The data folder contains two datasets:-

Bank.csv: 45,211 rows and 18 columns ordered by date (from May 2008 to November 2010)

Detailed Column Descriptions
bank client data:

1 - age (numeric)

2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",
"blue-collar","self-employed","retired","technician","services")

3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)

4 - education (categorical: "unknown","secondary","primary","tertiary")

5 - default: has credit in default? (binary: "yes","no")

6 - balance: average yearly balance, in euros (numeric)

7 - housing: has housing loan? (binary: "yes","no")

8 - loan: has personal loan? (binary: "yes","no")
# related with the last contact of the current campaign:
9 - contact: contact communication type (categorical: "unknown","telephone","cellular")
10 - day: last contact day of the month (numeric)

11 - month: last contact month of year (categorical: "jan", "feb", "mar", â€¦, "nov", "dec")

12 - duration: last contact duration, in seconds (numeric)

# other attributes:
13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)

14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)

15 - previous: number of contacts performed before this campaign and for this client (numeric)

16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")

Output variable (desired target):

17 - y - has the client subscribed a term deposit? (binary: "yes","no")

Missing Attribute Values: None

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/Bank.csv',sep = ';')
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143,yes,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,no,29,yes,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,no,2,yes,yes,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,no,1506,yes,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,no,1,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,no,825,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,no,1729,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,no,5715,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,no,668,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,no,2971,no,no,cellular,17,nov,361,2,188,11,other,no

In [2]:
print(df.shape)
df.info()
df.isnull().sum()

(45211, 17)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        45211 non-null  int64
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64
 12  campaign   45211 non-null  int64
 13  pdays      45211 non-null  int64
 14  previous   45211 non-null  int64
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [3]:
#For object check the data 
for cn in df.columns:
  if(df[cn].dtype==object):
    print(df[cn].value_counts())
    print('-'*40)

blue-collar      9732
management       9458
technician       7597
admin.           5171
services         4154
retired          2264
self-employed    1579
entrepreneur     1487
unemployed       1303
housemaid        1240
student           938
unknown           288
Name: job, dtype: int64
----------------------------------------
married     27214
single      12790
divorced     5207
Name: marital, dtype: int64
----------------------------------------
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: education, dtype: int64
----------------------------------------
no     44396
yes      815
Name: default, dtype: int64
----------------------------------------
yes    25130
no     20081
Name: housing, dtype: int64
----------------------------------------
no     37967
yes     7244
Name: loan, dtype: int64
----------------------------------------
cellular     29285
unknown      13020
telephone     2906
Name: contact, dtype: int64
----------------------------------------
may    13766
jul     6895
aug     6247
jun     5341
nov     3970
apr     2932
feb     2649
jan     1403
oct      738
sep      579
mar      477
dec      214
Name: month, dtype: int64
----------------------------------------
unknown    36959
failure     4901
other       1840
success     1511
Name: poutcome, dtype: int64
----------------------------------------
no     39922
yes     5289
Name: y, dtype: int64
----------------------------------------

In [4]:
def Encoder(df):
          from sklearn import preprocessing
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = preprocessing.LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df

In [5]:
df=Encoder(df)
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3,0
1,44,9,2,1,0,29,1,0,2,5,8,151,1,-1,0,3,0
2,33,2,1,1,0,2,1,1,2,5,8,76,1,-1,0,3,0
3,47,1,1,3,0,1506,1,0,2,5,8,92,1,-1,0,3,0
4,33,11,2,3,0,1,0,0,2,5,8,198,1,-1,0,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,0,17,9,977,3,-1,0,3,1
45207,71,5,0,0,0,1729,0,0,0,17,9,456,2,-1,0,3,1
45208,72,5,1,1,0,5715,0,0,0,17,9,1127,5,184,3,2,1
45209,57,1,1,1,0,668,0,0,1,17,9,508,4,-1,0,3,0
45210,37,2,1,1,0,2971,0,0,0,17,9,361,2,188,11,1,0

In [6]:
y = df['y'] #Output
X = df.drop('y',axis=1)
X

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,58,4,1,2,0,2143,1,0,2,5,8,261,1,-1,0,3
1,44,9,2,1,0,29,1,0,2,5,8,151,1,-1,0,3
2,33,2,1,1,0,2,1,1,2,5,8,76,1,-1,0,3
3,47,1,1,3,0,1506,1,0,2,5,8,92,1,-1,0,3
4,33,11,2,3,0,1,0,0,2,5,8,198,1,-1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,9,1,2,0,825,0,0,0,17,9,977,3,-1,0,3
45207,71,5,0,0,0,1729,0,0,0,17,9,456,2,-1,0,3
45208,72,5,1,1,0,5715,0,0,0,17,9,1127,5,184,3,2
45209,57,1,1,1,0,668,0,0,1,17,9,508,4,-1,0,3
45210,37,2,1,1,0,2971,0,0,0,17,9,361,2,188,11,1

In [7]:
from sklearn.model_selection import  train_test_split


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)

In [15]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
import lightgbm as lgb
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import accuracy_score, confusion_matrix

Q1)Using  Random Forest,XGBoost, Light GBM and Gradient Boosting Classifier with default parameters (no parameter specifications except random_state) calculate Accuracy on Test data. Which method gives the best accuracy on test data

**Answer**: Based on accuracy LightGMB gives more better results on test data.

In [9]:
#Random Forest
forest = RandomForestClassifier(random_state=17 )
forest.fit(X_train, y_train)
forest_pred = forest.predict(X_test)
print(accuracy_score(y_test, forest_pred) )
print(confusion_matrix(y_test, forest_pred)) 

#XGBoost
xgb = XGBClassifier(random_state=17)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)
print(accuracy_score(y_test, xgb_pred))
print(confusion_matrix(y_test, xgb_pred)) 

#LightGBM
lgb = lgb.LGBMClassifier(random_state=17)
lgb.fit(X_train, y_train)
lgb_pred = lgb.predict(X_test)
print(accuracy_score(y_test, lgb_pred))
print(confusion_matrix(y_test, lgb_pred))
      
#GradientBoosting
gbm = GradientBoostingClassifier(random_state=17)
gbm.fit(X_train, y_train)
gbm_pred = gbm.predict(X_test)
print(accuracy_score(y_test, gbm_pred))
print(confusion_matrix(y_test, gbm_pred))

0.9025037600636999
[[9635  319]
 [ 783  566]]
0.9043616738918872
[[9562  392]
 [ 689  660]]
0.9073697248518092
[[9601  353]
 [ 694  655]]
0.9018844554543042
[[9657  297]
 [ 812  537]]

Q2) Using optuna hyperparmeter optimization technique and 100 trial

 a)find best methods with  parameters  using Cross validation (CV=3) technique for the range of   parameters below. What are the best parameters for the method with highest cross validation accuracy?

"max_depth": range(2, 16), "max_features": range(2, 16)

 b)Evaluate the performance of the  method with highest cross validation accuracy on test data.What is the accuracy value?

In [10]:
import optuna

import sklearn.ensemble
import sklearn.model_selection
import sklearn.svm

In [11]:
def objective(trial):
    x, y = X_train,y_train

    classifier_name = trial.suggest_categorical("classifier", ["Random Forest","XGBoost", "LightGBM","GradientBoostingClassifier" ])
    if classifier_name == "Random Forest":
         from sklearn.ensemble import RandomForestClassifier
         max_depth = trial.suggest_int("max_depth", 2,X_train.shape[1])
         max_features = trial.suggest_int("max_features", 2,X_train.shape[1])
         classifier_obj = sklearn.ensemble.RandomForestClassifier(random_state=17,  max_depth=max_depth, max_features=max_features )
        
         

    elif classifier_name == "XGBoost":
         from xgboost import XGBClassifier
         max_depth = trial.suggest_int("max_depth", 2,X_train.shape[1])
         max_features = trial.suggest_int("max_features", 2,X_train.shape[1])
         classifier_obj = XGBClassifier(random_state=17,  max_depth=max_depth, max_features=max_features )
        
         

    elif classifier_name == "LightGBM":
         import lightgbm as lgb
         max_depth = trial.suggest_int("max_depth", 2,X_train.shape[1])
         max_features = trial.suggest_int("max_features", 2,X_train.shape[1])
         classifier_obj = lgb.LGBMClassifier(random_state=17,  max_depth=max_depth, max_features=max_features )
        
       
       
    else:
         max_depth = trial.suggest_int("max_depth", 2,X_train.shape[1])
         max_features = trial.suggest_int("max_features", 2,X_train.shape[1])
         classifier_obj = sklearn.ensemble.GradientBoostingClassifier(random_state=17,  max_depth=max_depth, max_features=max_features )
        
         

    accuracy=sklearn.model_selection.cross_val_score(classifier_obj, x, y, n_jobs=-1, cv=3).mean()
   
    return accuracy

In [12]:
if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

[I 2023-04-08 00:06:21,757] A new study created in memory with name: no-name-e597e51e-13c9-4c7a-bfd2-23d6edfcff72
[I 2023-04-08 00:06:27,735] Trial 0 finished with value: 0.9073080219248162 and parameters: {'classifier': 'LightGBM', 'max_depth': 16, 'max_features': 14}. Best is trial 0 with value: 0.9073080219248162.
[I 2023-04-08 00:06:29,884] Trial 1 finished with value: 0.9009083817916711 and parameters: {'classifier': 'LightGBM', 'max_depth': 2, 'max_features': 2}. Best is trial 0 with value: 0.9073080219248162.
[I 2023-04-08 00:06:51,290] Trial 2 finished with value: 0.903444612932636 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 14, 'max_features': 4}. Best is trial 0 with value: 0.9073080219248162.
[I 2023-04-08 00:06:58,146] Trial 3 finished with value: 0.9017931313649131 and parameters: {'classifier': 'XGBoost', 'max_depth': 11, 'max_features': 2}. Best is trial 0 with value: 0.9073080219248162.
[I 2023-04-08 00:07:03,248] Trial 4 finished with value: 0.9044768629523222 and parameters: {'classifier': 'Random Forest', 'max_depth': 8, 'max_features': 9}. Best is trial 0 with value: 0.9073080219248162.
[I 2023-04-08 00:07:07,461] Trial 5 finished with value: 0.9054206017449381 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 6, 'max_features': 6}. Best is trial 0 with value: 0.9073080219248162.
[I 2023-04-08 00:07:08,048] Trial 6 finished with value: 0.9073964914025385 and parameters: {'classifier': 'LightGBM', 'max_depth': 6, 'max_features': 3}. Best is trial 6 with value: 0.9073964914025385.
[I 2023-04-08 00:07:11,188] Trial 7 finished with value: 0.9058629491335495 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 5, 'max_features': 7}. Best is trial 6 with value: 0.9073964914025385.
[I 2023-04-08 00:07:13,102] Trial 8 finished with value: 0.9018521127562842 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 2, 'max_features': 10}. Best is trial 6 with value: 0.9073964914025385.
[I 2023-04-08 00:07:39,481] Trial 9 finished with value: 0.9019995323133664 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 15, 'max_features': 2}. Best is trial 6 with value: 0.9073964914025385.
[I 2023-04-08 00:07:40,919] Trial 10 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 16}. Best is trial 10 with value: 0.9076029654123507.
[I 2023-04-08 00:07:42,451] Trial 11 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 16}. Best is trial 10 with value: 0.9076029654123507.
[I 2023-04-08 00:07:43,972] Trial 12 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 16}. Best is trial 10 with value: 0.9076029654123507.
[I 2023-04-08 00:07:45,585] Trial 13 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:07:53,044] Trial 14 finished with value: 0.901439243016687 and parameters: {'classifier': 'XGBoost', 'max_depth': 13, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:07:58,509] Trial 15 finished with value: 0.9045063484293392 and parameters: {'classifier': 'Random Forest', 'max_depth': 9, 'max_features': 12}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:07:59,091] Trial 16 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 14}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:07:59,706] Trial 17 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 12}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:00,320] Trial 18 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 14}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:04,314] Trial 19 finished with value: 0.9040640140873991 and parameters: {'classifier': 'XGBoost', 'max_depth': 8, 'max_features': 11}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:13,467] Trial 20 finished with value: 0.9024419031859862 and parameters: {'classifier': 'Random Forest', 'max_depth': 16, 'max_features': 14}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:14,940] Trial 21 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 12}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:15,554] Trial 22 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 11}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:16,167] Trial 23 finished with value: 0.9070425717423013 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 10}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:17,757] Trial 24 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 7}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:19,178] Trial 25 finished with value: 0.9072195759311023 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 15}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:19,751] Trial 26 finished with value: 0.9068656327868568 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:20,413] Trial 27 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 11}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:25,003] Trial 28 finished with value: 0.9050077215680039 and parameters: {'classifier': 'Random Forest', 'max_depth': 10, 'max_features': 9}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:25,644] Trial 29 finished with value: 0.9073080219248162 and parameters: {'classifier': 'LightGBM', 'max_depth': 16, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:33,832] Trial 30 finished with value: 0.9011443569345059 and parameters: {'classifier': 'XGBoost', 'max_depth': 15, 'max_features': 15}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:34,448] Trial 31 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 7}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:35,035] Trial 32 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 7}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:35,618] Trial 33 finished with value: 0.9068656327868568 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 5}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:36,253] Trial 34 finished with value: 0.9070425717423013 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 8}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:36,853] Trial 35 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 11}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:37,450] Trial 36 finished with value: 0.9064527760939308 and parameters: {'classifier': 'LightGBM', 'max_depth': 8, 'max_features': 10}. Best is trial 13 with value: 0.9079273656742256.

[I 2023-04-08 00:08:38,021] Trial 37 finished with value: 0.9068656327868568 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 5}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:43,282] Trial 38 finished with value: 0.9025304013663851 and parameters: {'classifier': 'XGBoost', 'max_depth': 10, 'max_features': 8}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:08:52,788] Trial 39 finished with value: 0.9025304039757195 and parameters: {'classifier': 'Random Forest', 'max_depth': 15, 'max_features': 15}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:08,180] Trial 40 finished with value: 0.9039459965086376 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 12, 'max_features': 9}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:08,780] Trial 41 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 11}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:09,411] Trial 42 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:10,024] Trial 43 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 12}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:10,496] Trial 44 finished with value: 0.9049487610513068 and parameters: {'classifier': 'LightGBM', 'max_depth': 3, 'max_features': 11}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:25,356] Trial 45 finished with value: 0.9014687337123726 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 11, 'max_features': 14}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:25,988] Trial 46 finished with value: 0.9076324091400197 and parameters: {'classifier': 'LightGBM', 'max_depth': 7, 'max_features': 10}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:26,604] Trial 47 finished with value: 0.9068656327868568 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 6}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:27,204] Trial 48 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 8}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:27,804] Trial 49 finished with value: 0.9072195759311023 and parameters: {'classifier': 'LightGBM', 'max_depth': 9, 'max_features': 9}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:41,311] Trial 50 finished with value: 0.9022650007612211 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 11, 'max_features': 12}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:42,020] Trial 51 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 7}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:42,725] Trial 52 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 6}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:43,321] Trial 53 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:43,793] Trial 54 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 6}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:49,224] Trial 55 finished with value: 0.901439243016687 and parameters: {'classifier': 'XGBoost', 'max_depth': 13, 'max_features': 4}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:53,912] Trial 56 finished with value: 0.9044178659049457 and parameters: {'classifier': 'Random Forest', 'max_depth': 10, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:54,375] Trial 57 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 14}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:54,814] Trial 58 finished with value: 0.9068656327868568 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 5}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:55,272] Trial 59 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 8}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:55,750] Trial 60 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 15}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:56,238] Trial 61 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 7}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:56,717] Trial 62 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 7}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:57,176] Trial 63 finished with value: 0.9070425717423013 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 9}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:57,648] Trial 64 finished with value: 0.9076914087967306 and parameters: {'classifier': 'LightGBM', 'max_depth': 15, 'max_features': 6}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:09:58,137] Trial 65 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 10}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:03,149] Trial 66 finished with value: 0.9029727565829994 and parameters: {'classifier': 'XGBoost', 'max_depth': 12, 'max_features': 8}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:05,402] Trial 67 finished with value: 0.9052141277351257 and parameters: {'classifier': 'Random Forest', 'max_depth': 13, 'max_features': 4}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:05,859] Trial 68 finished with value: 0.9068656327868568 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:14,366] Trial 69 finished with value: 0.901970052055018 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 9, 'max_features': 16}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:14,823] Trial 70 finished with value: 0.9070425717423013 and parameters: {'classifier': 'LightGBM', 'max_depth': 10, 'max_features': 11}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:15,280] Trial 71 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 11}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:15,739] Trial 72 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 12}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:16,212] Trial 73 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 11}. Best is trial 13 with value: 0.9079273656742256.

[I 2023-04-08 00:10:16,668] Trial 74 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 10}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:17,143] Trial 75 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 12}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:17,617] Trial 76 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 14}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:18,153] Trial 77 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 7}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:18,612] Trial 78 finished with value: 0.9068656327868568 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 9}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:23,938] Trial 79 finished with value: 0.901439243016687 and parameters: {'classifier': 'XGBoost', 'max_depth': 13, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:29,018] Trial 80 finished with value: 0.9049782204349813 and parameters: {'classifier': 'Random Forest', 'max_depth': 11, 'max_features': 12}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:29,456] Trial 81 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 14}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:29,883] Trial 82 finished with value: 0.9056859710380912 and parameters: {'classifier': 'LightGBM', 'max_depth': 5, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:30,355] Trial 83 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 15}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:30,862] Trial 84 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 10}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:31,330] Trial 85 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 11}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:39,754] Trial 86 finished with value: 0.902500934154708 and parameters: {'classifier': 'GradientBoostingClassifier', 'max_depth': 10, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:40,241] Trial 87 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 8}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:40,700] Trial 88 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 14}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:41,154] Trial 89 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 12}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:41,595] Trial 90 finished with value: 0.9068656327868568 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 6}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:42,054] Trial 91 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 7}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:42,547] Trial 92 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 9}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:43,050] Trial 93 finished with value: 0.9076029654123507 and parameters: {'classifier': 'LightGBM', 'max_depth': 11, 'max_features': 8}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:43,525] Trial 94 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 8}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:43,999] Trial 95 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 7}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:44,471] Trial 96 finished with value: 0.9076618893983683 and parameters: {'classifier': 'LightGBM', 'max_depth': 13, 'max_features': 8}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:44,946] Trial 97 finished with value: 0.9079273656742256 and parameters: {'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 15}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:49,243] Trial 98 finished with value: 0.9017931313649131 and parameters: {'classifier': 'XGBoost', 'max_depth': 11, 'max_features': 13}. Best is trial 13 with value: 0.9079273656742256.
[I 2023-04-08 00:10:49,717] Trial 99 finished with value: 0.9068656327868568 and parameters: {'classifier': 'LightGBM', 'max_depth': 14, 'max_features': 5}. Best is trial 13 with value: 0.9079273656742256.

FrozenTrial(number=13, state=TrialState.COMPLETE, values=[0.9079273656742256], datetime_start=datetime.datetime(2023, 4, 8, 0, 7, 43, 974013), datetime_complete=datetime.datetime(2023, 4, 8, 0, 7, 45, 585301), params={'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 13}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'classifier': CategoricalDistribution(choices=('Random Forest', 'XGBoost', 'LightGBM', 'GradientBoostingClassifier')), 'max_depth': IntDistribution(high=16, log=False, low=2, step=1), 'max_features': IntDistribution(high=16, log=False, low=2, step=1)}, trial_id=13, value=None)

In [13]:
study.best_params

{'classifier': 'LightGBM', 'max_depth': 12, 'max_features': 13}

In [17]:
import lightgbm as lgb
lgb_opt = lgb.LGBMClassifier(random_state=17, max_depth=12, max_features=3)
lgb_opt.fit(X_train, y_train)
lgb_opt_pred = lgb_opt.predict(X_test)
print(accuracy_score(y_test, lgb_opt_pred))
print(confusion_matrix(y_test, lgb_opt_pred))

[LightGBM] [Warning] Unknown parameter: max_features
0.9062195877200743
[[9588  366]
 [ 694  655]]

In [18]:
def objective(trial):
    x, y = X_train,y_train

    param = {
        "objective": "binary",
        "verbosity": -1,
        "boosting_type": "gbdt",
        "max_dept" :trial.suggest_int("max_depth", 2, X_train.shape[1]),
        "max_features" : trial.suggest_int("max_features", 2,X_train.shape[1]),       
        "num_leaves": trial.suggest_int("num_leaves", 2, 256),
        "feature_fraction": trial.suggest_float("feature_fraction", 0.4, 1.0),
        "bagging_fraction": trial.suggest_float("bagging_fraction", 0.4, 1.0),
        "bagging_freq": trial.suggest_int("bagging_freq", 1, 7),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
    }
    import lightgbm as lgb
    classifier_obj = lgb.LGBMClassifier(random_state=17,**param)

    accuracy=sklearn.model_selection.cross_val_score(classifier_obj, x, y, n_jobs=-1, cv=3).mean()
   
    return accuracy

In [ ]:
if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

In [ ]:
 print(study.best_params)

In [19]:
import lightgbm as lgb

model = lgb.LGBMClassifier(random_state=17,**study.best_params)
model.fit(X_train, y_train)
xgb_pred = model.predict(X_test)
accuracy_score(y_test, xgb_pred)

[LightGBM] [Warning] Unknown parameter: classifier
[LightGBM] [Warning] Unknown parameter: max_features

0.9062195877200743

For Q3 and Q4 ,use the following data.

In [20]:
dr=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/diamond.csv')
dr

,Carat Weight,Cut,Color,Clarity,Polish,Symmetry,Report,Price
0,1.10,Ideal,H,SI1,VG,EX,GIA,5169
1,0.83,Ideal,H,VS1,ID,ID,AGSL,3470
2,0.85,Ideal,H,SI1,EX,EX,GIA,3183
3,0.91,Ideal,E,SI1,VG,VG,GIA,4370
4,0.83,Ideal,G,SI1,EX,EX,GIA,3171
...,...,...,...,...,...,...,...,...
5995,1.03,Ideal,D,SI1,EX,EX,GIA,6250
5996,1.00,Very Good,D,SI1,VG,VG,GIA,5328
5997,1.02,Ideal,D,SI1,EX,EX,GIA,6157
5998,1.27,Signature-Ideal,G,VS1,EX,EX,GIA,11206
5999,2.19,Ideal,E,VS1,EX,EX,GIA,30507

In [21]:
def Encoder(df):
          from sklearn import preprocessing
          columnsToEncode = list(df.select_dtypes(include=['category','object']))
          le = preprocessing.LabelEncoder()
          for feature in columnsToEncode:
              try:
                  df[feature] = le.fit_transform(df[feature])
              except:
                  print('Error encoding '+feature)
          return df

In [22]:
dr=Encoder(dr)
dr

      Carat Weight  Cut  Color  Clarity  Polish  Symmetry  Report  Price
0             1.10    2      4        2       3         0       1   5169
1             0.83    2      4        3       2         2       0   3470
2             0.85    2      4        2       0         0       1   3183
3             0.91    2      1        2       3         3       1   4370
4             0.83    2      3        2       0         0       1   3171
...            ...  ...    ...      ...     ...       ...     ...    ...
5995          1.03    2      0        2       0         0       1   6250
5996          1.00    4      0        2       3         3       1   5328
5997          1.02    2      0        2       0         0       1   6157
5998          1.27    3      3        3       0         0       1  11206
5999          2.19    2      1        3       0         0       1  30507

[6000 rows x 8 columns]

In [23]:
y = dr['Price'] #Output
X = dr.drop('Price',axis=1)
X

      Carat Weight  Cut  Color  Clarity  Polish  Symmetry  Report
0             1.10    2      4        2       3         0       1
1             0.83    2      4        3       2         2       0
2             0.85    2      4        2       0         0       1
3             0.91    2      1        2       3         3       1
4             0.83    2      3        2       0         0       1
...            ...  ...    ...      ...     ...       ...     ...
5995          1.03    2      0        2       0         0       1
5996          1.00    4      0        2       3         3       1
5997          1.02    2      0        2       0         0       1
5998          1.27    3      3        3       0         0       1
5999          2.19    2      1        3       0         0       1

[6000 rows x 7 columns]

In [24]:
from sklearn.model_selection import  train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=17)

Q3)Using Linear Regression,Decison Tree Random Forest,XGBoost, Light GBM and Gradient Boosting Classifier with default parameters (no parameter specifications except random_state) calculate R2 statistics on test data. Which method gives the best accuracy on test data

In [25]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
import lightgbm as lgb
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score

In [28]:
#Linear Regression
lr = LinearRegression()
lr.fit(X_train,y_train)
lr_pred = lr.predict(X_test)
print(r2_score(y_test, lr_pred))

#DecisionTree
tree = DecisionTreeRegressor(random_state=17)
tree.fit(X_train,y_train)
tree_pred = tree.predict(X_test)
print(r2_score(y_test, tree_pred))

#RandomForestRegressor
forest = RandomForestRegressor(random_state=17 )
forest.fit(X_train, y_train)
forest_pred = forest.predict(X_test)
print(r2_score(y_test, forest_pred))


#XGBoost
xgb = XGBRegressor(random_state=17)
xgb.fit(X_train, y_train)
xgb_pred = xgb.predict(X_test)
print(r2_score(y_test, xgb_pred))

#LightGBM
lgr = lgb.LGBMRegressor(random_state=17)
lgr.fit(X_train, y_train)
lgr_pred = lgr.predict(X_test)
print(r2_score(y_test, lgr_pred))

      
#GradientBoosting
gbr = GradientBoostingRegressor(random_state=17)
gbr.fit(X_train, y_train)
gbr_pred = gbr.predict(X_test)
print(r2_score(y_test, gbr_pred))

0.823384582969696
0.95923297527452
0.9799660276771226
0.9803113835881238
0.9812609895578275
0.9739035655494326

Q4) Using optuna hyperparmeter optimization technique (100 trial)  with Random Forest,XGBoost, Light GBM and Gradient Boosting Regressor

a)find best methods with  parameters  using Cross validation (CV=3) technique for the range of   parameters below. What are the best parameters for the method with highest cross validation R2?

"max_depth": range(2, 7), "max_features": range(2, 7)

 b)Evaluate the performance of the  method with highest cross validation R2 on test data. What is the R2 value?

In [29]:
def objective(trial):
    x, y = X_train,y_train

    regressor_name = trial.suggest_categorical("regressor", ["GradientBoosting", "XGBoost","LightGBM","RandomForest"])
    if regressor_name == "GradientBoosting":
         max_depth = trial.suggest_int("max_depth", 2,16)
         max_features = trial.suggest_int("max_features", 2,X_train.shape[1])
         regressor_obj = sklearn.ensemble.GradientBoostingRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
    
    elif regressor_name == "XGBoost":
         from xgboost import XGBRegressor
         max_depth = trial.suggest_int("max_depth", 2,X_train.shape[1])
         max_features = trial.suggest_int("max_features", 2,X_train.shape[1])
         regressor_obj = XGBRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
        
    if regressor_name == "Random Forest":
         from sklearn.ensemble import RandomForestRegressor
         max_depth = trial.suggest_int("max_depth", 2,X_train.shape[1])
         max_features = trial.suggest_int("max_features", 2,X_train.shape[1])
         classifier_obj = sklearn.ensemble.RandomForestRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )    

    elif regressor_name == "LightGBM":
         import lightgbm as lgb
         max_depth = trial.suggest_int("max_depth", 2,X_train.shape[1])
         max_features = trial.suggest_int("max_features", 2,X_train.shape[1])
         regressor_obj = lgb.LGBMRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )
        
       
   
    else:
         max_depth = trial.suggest_int("max_depth", 2,16)
         max_features = trial.suggest_int("max_features", 2,X_train.shape[1])
         regressor_obj = sklearn.ensemble.RandomForestRegressor(random_state=17,  max_depth=max_depth, max_features=max_features )

     

    r2=sklearn.model_selection.cross_val_score(regressor_obj, x, y, n_jobs=-1, cv=3).mean()
   
    return r2


if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=20)
    print(study.best_trial)

[I 2023-04-08 00:13:32,777] A new study created in memory with name: no-name-8790a117-4b90-430b-88a9-673f31901728
C:\Users\abdul\anaconda3\lib\site-packages\optuna\trial\_trial.py:681: RuntimeWarning: Inconsistent parameter values for distribution with name "max_depth"! This might be a configuration mistake. Optuna allows to call the same distribution with the same name more than once in a trial. When the parameter values are inconsistent optuna only uses the values of the first call and ignores all following. Using these values: {'log': False, 'step': 1, 'low': 2, 'high': 7}
  warnings.warn(
[I 2023-04-08 00:13:32,904] Trial 0 finished with value: 0.68051387739466 and parameters: {'regressor': 'XGBoost', 'max_depth': 2, 'max_features': 3}. Best is trial 0 with value: 0.68051387739466.
[I 2023-04-08 00:13:33,369] Trial 1 finished with value: 0.9807117899265797 and parameters: {'regressor': 'RandomForest', 'max_depth': 16, 'max_features': 6}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:33,410] Trial 2 finished with value: 0.9761140473772666 and parameters: {'regressor': 'LightGBM', 'max_depth': 4, 'max_features': 3}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:33,470] Trial 3 finished with value: 0.9758296442252078 and parameters: {'regressor': 'LightGBM', 'max_depth': 7, 'max_features': 6}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:33,514] Trial 4 finished with value: 0.9761140473772666 and parameters: {'regressor': 'LightGBM', 'max_depth': 4, 'max_features': 5}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:33,760] Trial 5 finished with value: 0.9720558623263608 and parameters: {'regressor': 'XGBoost', 'max_depth': 7, 'max_features': 6}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:33,808] Trial 6 finished with value: 0.9765224083258769 and parameters: {'regressor': 'LightGBM', 'max_depth': 5, 'max_features': 5}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:33,865] Trial 7 finished with value: 0.9758296442252078 and parameters: {'regressor': 'LightGBM', 'max_depth': 7, 'max_features': 5}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:33,993] Trial 8 finished with value: 0.7430594344013942 and parameters: {'regressor': 'XGBoost', 'max_depth': 2, 'max_features': 4}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:34,130] Trial 9 finished with value: 0.68051387739466 and parameters: {'regressor': 'RandomForest', 'max_depth': 2, 'max_features': 3}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:34,665] Trial 10 finished with value: 0.9794516997382194 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 16, 'max_features': 7}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:35,174] Trial 11 finished with value: 0.9794516997382194 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 16, 'max_features': 7}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:35,687] Trial 12 finished with value: 0.9794516997382194 and parameters: {'regressor': 'RandomForest', 'max_depth': 16, 'max_features': 7}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:36,115] Trial 13 finished with value: 0.9802738944351855 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 13, 'max_features': 6}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:36,551] Trial 14 finished with value: 0.9802738944351855 and parameters: {'regressor': 'RandomForest', 'max_depth': 13, 'max_features': 6}. Best is trial 1 with value: 0.9807117899265797.
[I 2023-04-08 00:13:36,949] Trial 15 finished with value: 0.9810002822538967 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 12, 'max_features': 6}. Best is trial 15 with value: 0.9810002822538967.
[I 2023-04-08 00:13:37,202] Trial 16 finished with value: 0.9574970113010587 and parameters: {'regressor': 'RandomForest', 'max_depth': 12, 'max_features': 2}. Best is trial 15 with value: 0.9810002822538967.
[I 2023-04-08 00:13:37,521] Trial 17 finished with value: 0.9795357597218017 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 12, 'max_features': 4}. Best is trial 15 with value: 0.9810002822538967.
[I 2023-04-08 00:13:37,868] Trial 18 finished with value: 0.9797840689647774 and parameters: {'regressor': 'GradientBoosting', 'max_depth': 10, 'max_features': 6}. Best is trial 15 with value: 0.9810002822538967.
[I 2023-04-08 00:13:38,352] Trial 19 finished with value: 0.9795491687128212 and parameters: {'regressor': 'RandomForest', 'max_depth': 14, 'max_features': 7}. Best is trial 15 with value: 0.9810002822538967.

FrozenTrial(number=15, state=TrialState.COMPLETE, values=[0.9810002822538967], datetime_start=datetime.datetime(2023, 4, 8, 0, 13, 36, 552871), datetime_complete=datetime.datetime(2023, 4, 8, 0, 13, 36, 949105), params={'regressor': 'GradientBoosting', 'max_depth': 12, 'max_features': 6}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'regressor': CategoricalDistribution(choices=('GradientBoosting', 'XGBoost', 'LightGBM', 'RandomForest')), 'max_depth': IntDistribution(high=16, log=False, low=2, step=1), 'max_features': IntDistribution(high=7, log=False, low=2, step=1)}, trial_id=15, value=None)

In [30]:
 print(study.best_params)

{'regressor': 'GradientBoosting', 'max_depth': 12, 'max_features': 6}

In [32]:
gbr = GradientBoostingRegressor(random_state=17,max_depth=12, max_features=6)
gbr.fit(X_train, y_train)
gbr_pred = gbr.predict(X_test)
print(r2_score(y_test, gbr_pred))

0.975702345530772